//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4952
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.oorsprong.org/websamples.countryinfo", ClrNamespace="www.oorsprong.org.websamples.countryinfo")]

namespace www.oorsprong.org.websamples.countryinfo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tContinent : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string sCodeField;
        
        private string sNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sCode
        {
            get
            {
                return this.sCodeField;
            }
            set
            {
                this.sCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCurrency : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string sISOCodeField;
        
        private string sNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryCodeAndName", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryCodeAndName : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string sISOCodeField;
        
        private string sNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryCodeAndNameGroupedByContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryCodeAndNameGroupedByContinent : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private www.oorsprong.org.websamples.countryinfo.tContinent ContinentField;
        
        private www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] CountryCodeAndNamesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public www.oorsprong.org.websamples.countryinfo.tContinent Continent
        {
            get
            {
                return this.ContinentField;
            }
            set
            {
                this.ContinentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] CountryCodeAndNames
        {
            get
            {
                return this.CountryCodeAndNamesField;
            }
            set
            {
                this.CountryCodeAndNamesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryInfo", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string sISOCodeField;
        
        private string sNameField;
        
        private string sCapitalCityField;
        
        private string sPhoneCodeField;
        
        private string sContinentCodeField;
        
        private string sCurrencyISOCodeField;
        
        private string sCountryFlagField;
        
        private www.oorsprong.org.websamples.countryinfo.tLanguage[] LanguagesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string sCapitalCity
        {
            get
            {
                return this.sCapitalCityField;
            }
            set
            {
                this.sCapitalCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string sPhoneCode
        {
            get
            {
                return this.sPhoneCodeField;
            }
            set
            {
                this.sPhoneCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string sContinentCode
        {
            get
            {
                return this.sContinentCodeField;
            }
            set
            {
                this.sContinentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string sCurrencyISOCode
        {
            get
            {
                return this.sCurrencyISOCodeField;
            }
            set
            {
                this.sCurrencyISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string sCountryFlag
        {
            get
            {
                return this.sCountryFlagField;
            }
            set
            {
                this.sCountryFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public www.oorsprong.org.websamples.countryinfo.tLanguage[] Languages
        {
            get
            {
                return this.LanguagesField;
            }
            set
            {
                this.LanguagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tLanguage", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tLanguage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string sISOCodeField;
        
        private string sNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo", ConfigurationName="CountryInfoServiceSoapType")]
public interface CountryInfoServiceSoapType
{
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListOfContinentsByNameResult del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    ListOfContinentsByNameResponse ListOfContinentsByName(ListOfContinentsByNameRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListOfContinentsByCodeResult del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    ListOfContinentsByCodeResponse ListOfContinentsByCode(ListOfContinentsByCodeRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListOfCurrenciesByNameResult del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    ListOfCurrenciesByNameResponse ListOfCurrenciesByName(ListOfCurrenciesByNameRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListOfCurrenciesByCodeResult del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    ListOfCurrenciesByCodeResponse ListOfCurrenciesByCode(ListOfCurrenciesByCodeRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sCurrencyISOCode del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    CurrencyNameResponse CurrencyName(CurrencyNameRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListOfCountryNamesByCodeResult del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    ListOfCountryNamesByCodeResponse ListOfCountryNamesByCode(ListOfCountryNamesByCodeRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListOfCountryNamesByNameResult del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    ListOfCountryNamesByNameResponse ListOfCountryNamesByName(ListOfCountryNamesByNameRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListOfCountryNamesGroupedByContinentResult del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    ListOfCountryNamesGroupedByContinentResponse ListOfCountryNamesGroupedByContinent(ListOfCountryNamesGroupedByContinentRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sCountryISOCode del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    CountryNameResponse CountryName(CountryNameRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sCountryName del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    CountryISOCodeResponse CountryISOCode(CountryISOCodeRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sCountryISOCode del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    CapitalCityResponse CapitalCity(CapitalCityRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sCountryISOCode del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    CountryCurrencyResponse CountryCurrency(CountryCurrencyRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sCountryISOCode del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    CountryFlagResponse CountryFlag(CountryFlagRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sCountryISOCode del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    CountryIntPhoneCodeResponse CountryIntPhoneCode(CountryIntPhoneCodeRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sCountryISOCode del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    FullCountryInfoResponse FullCountryInfo(FullCountryInfoRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FullCountryInfoAllCountriesResult del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    FullCountryInfoAllCountriesResponse FullCountryInfoAllCountries(FullCountryInfoAllCountriesRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sISOCurrencyCode del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    CountriesUsingCurrencyResponse CountriesUsingCurrency(CountriesUsingCurrencyRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListOfLanguagesByNameResult del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    ListOfLanguagesByNameResponse ListOfLanguagesByName(ListOfLanguagesByNameRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListOfLanguagesByCodeResult del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    ListOfLanguagesByCodeResponse ListOfLanguagesByCode(ListOfLanguagesByCodeRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sISOCode del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    LanguageNameResponse LanguageName(LanguageNameRequest request);
    
    // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sLanguageName del espacio de nombres http://www.oorsprong.org/websamples.countryinfo no está marcado para aceptar valores nil.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    LanguageISOCodeResponse LanguageISOCode(LanguageISOCodeRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfContinentsByNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfContinentsByNameRequestBody Body;
    
    public ListOfContinentsByNameRequest()
    {
    }
    
    public ListOfContinentsByNameRequest(ListOfContinentsByNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfContinentsByNameRequestBody
{
    
    public ListOfContinentsByNameRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfContinentsByNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfContinentsByNameResponseBody Body;
    
    public ListOfContinentsByNameResponse()
    {
    }
    
    public ListOfContinentsByNameResponse(ListOfContinentsByNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfContinentsByNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tContinent[] ListOfContinentsByNameResult;
    
    public ListOfContinentsByNameResponseBody()
    {
    }
    
    public ListOfContinentsByNameResponseBody(www.oorsprong.org.websamples.countryinfo.tContinent[] ListOfContinentsByNameResult)
    {
        this.ListOfContinentsByNameResult = ListOfContinentsByNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfContinentsByCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfContinentsByCodeRequestBody Body;
    
    public ListOfContinentsByCodeRequest()
    {
    }
    
    public ListOfContinentsByCodeRequest(ListOfContinentsByCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfContinentsByCodeRequestBody
{
    
    public ListOfContinentsByCodeRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfContinentsByCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfContinentsByCodeResponseBody Body;
    
    public ListOfContinentsByCodeResponse()
    {
    }
    
    public ListOfContinentsByCodeResponse(ListOfContinentsByCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfContinentsByCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tContinent[] ListOfContinentsByCodeResult;
    
    public ListOfContinentsByCodeResponseBody()
    {
    }
    
    public ListOfContinentsByCodeResponseBody(www.oorsprong.org.websamples.countryinfo.tContinent[] ListOfContinentsByCodeResult)
    {
        this.ListOfContinentsByCodeResult = ListOfContinentsByCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCurrenciesByNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCurrenciesByNameRequestBody Body;
    
    public ListOfCurrenciesByNameRequest()
    {
    }
    
    public ListOfCurrenciesByNameRequest(ListOfCurrenciesByNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfCurrenciesByNameRequestBody
{
    
    public ListOfCurrenciesByNameRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCurrenciesByNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCurrenciesByNameResponseBody Body;
    
    public ListOfCurrenciesByNameResponse()
    {
    }
    
    public ListOfCurrenciesByNameResponse(ListOfCurrenciesByNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfCurrenciesByNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCurrency[] ListOfCurrenciesByNameResult;
    
    public ListOfCurrenciesByNameResponseBody()
    {
    }
    
    public ListOfCurrenciesByNameResponseBody(www.oorsprong.org.websamples.countryinfo.tCurrency[] ListOfCurrenciesByNameResult)
    {
        this.ListOfCurrenciesByNameResult = ListOfCurrenciesByNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCurrenciesByCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCurrenciesByCodeRequestBody Body;
    
    public ListOfCurrenciesByCodeRequest()
    {
    }
    
    public ListOfCurrenciesByCodeRequest(ListOfCurrenciesByCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfCurrenciesByCodeRequestBody
{
    
    public ListOfCurrenciesByCodeRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCurrenciesByCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCurrenciesByCodeResponseBody Body;
    
    public ListOfCurrenciesByCodeResponse()
    {
    }
    
    public ListOfCurrenciesByCodeResponse(ListOfCurrenciesByCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfCurrenciesByCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCurrency[] ListOfCurrenciesByCodeResult;
    
    public ListOfCurrenciesByCodeResponseBody()
    {
    }
    
    public ListOfCurrenciesByCodeResponseBody(www.oorsprong.org.websamples.countryinfo.tCurrency[] ListOfCurrenciesByCodeResult)
    {
        this.ListOfCurrenciesByCodeResult = ListOfCurrenciesByCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CurrencyNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CurrencyNameRequestBody Body;
    
    public CurrencyNameRequest()
    {
    }
    
    public CurrencyNameRequest(CurrencyNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CurrencyNameRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCurrencyISOCode;
    
    public CurrencyNameRequestBody()
    {
    }
    
    public CurrencyNameRequestBody(string sCurrencyISOCode)
    {
        this.sCurrencyISOCode = sCurrencyISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CurrencyNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CurrencyNameResponseBody Body;
    
    public CurrencyNameResponse()
    {
    }
    
    public CurrencyNameResponse(CurrencyNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CurrencyNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CurrencyNameResult;
    
    public CurrencyNameResponseBody()
    {
    }
    
    public CurrencyNameResponseBody(string CurrencyNameResult)
    {
        this.CurrencyNameResult = CurrencyNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesByCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesByCodeRequestBody Body;
    
    public ListOfCountryNamesByCodeRequest()
    {
    }
    
    public ListOfCountryNamesByCodeRequest(ListOfCountryNamesByCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfCountryNamesByCodeRequestBody
{
    
    public ListOfCountryNamesByCodeRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesByCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesByCodeResponseBody Body;
    
    public ListOfCountryNamesByCodeResponse()
    {
    }
    
    public ListOfCountryNamesByCodeResponse(ListOfCountryNamesByCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfCountryNamesByCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] ListOfCountryNamesByCodeResult;
    
    public ListOfCountryNamesByCodeResponseBody()
    {
    }
    
    public ListOfCountryNamesByCodeResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] ListOfCountryNamesByCodeResult)
    {
        this.ListOfCountryNamesByCodeResult = ListOfCountryNamesByCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesByNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesByNameRequestBody Body;
    
    public ListOfCountryNamesByNameRequest()
    {
    }
    
    public ListOfCountryNamesByNameRequest(ListOfCountryNamesByNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfCountryNamesByNameRequestBody
{
    
    public ListOfCountryNamesByNameRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesByNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesByNameResponseBody Body;
    
    public ListOfCountryNamesByNameResponse()
    {
    }
    
    public ListOfCountryNamesByNameResponse(ListOfCountryNamesByNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfCountryNamesByNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] ListOfCountryNamesByNameResult;
    
    public ListOfCountryNamesByNameResponseBody()
    {
    }
    
    public ListOfCountryNamesByNameResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] ListOfCountryNamesByNameResult)
    {
        this.ListOfCountryNamesByNameResult = ListOfCountryNamesByNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesGroupedByContinentRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesGroupedByContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesGroupedByContinentRequestBody Body;
    
    public ListOfCountryNamesGroupedByContinentRequest()
    {
    }
    
    public ListOfCountryNamesGroupedByContinentRequest(ListOfCountryNamesGroupedByContinentRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfCountryNamesGroupedByContinentRequestBody
{
    
    public ListOfCountryNamesGroupedByContinentRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfCountryNamesGroupedByContinentResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesGroupedByContinentResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfCountryNamesGroupedByContinentResponseBody Body;
    
    public ListOfCountryNamesGroupedByContinentResponse()
    {
    }
    
    public ListOfCountryNamesGroupedByContinentResponse(ListOfCountryNamesGroupedByContinentResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfCountryNamesGroupedByContinentResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndNameGroupedByContinent[] ListOfCountryNamesGroupedByContinentResult;
    
    public ListOfCountryNamesGroupedByContinentResponseBody()
    {
    }
    
    public ListOfCountryNamesGroupedByContinentResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryCodeAndNameGroupedByContinent[] ListOfCountryNamesGroupedByContinentResult)
    {
        this.ListOfCountryNamesGroupedByContinentResult = ListOfCountryNamesGroupedByContinentResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryNameRequestBody Body;
    
    public CountryNameRequest()
    {
    }
    
    public CountryNameRequest(CountryNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryNameRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public CountryNameRequestBody()
    {
    }
    
    public CountryNameRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryNameResponseBody Body;
    
    public CountryNameResponse()
    {
    }
    
    public CountryNameResponse(CountryNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryNameResult;
    
    public CountryNameResponseBody()
    {
    }
    
    public CountryNameResponseBody(string CountryNameResult)
    {
        this.CountryNameResult = CountryNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryISOCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryISOCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryISOCodeRequestBody Body;
    
    public CountryISOCodeRequest()
    {
    }
    
    public CountryISOCodeRequest(CountryISOCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryISOCodeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryName;
    
    public CountryISOCodeRequestBody()
    {
    }
    
    public CountryISOCodeRequestBody(string sCountryName)
    {
        this.sCountryName = sCountryName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryISOCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryISOCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryISOCodeResponseBody Body;
    
    public CountryISOCodeResponse()
    {
    }
    
    public CountryISOCodeResponse(CountryISOCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryISOCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryISOCodeResult;
    
    public CountryISOCodeResponseBody()
    {
    }
    
    public CountryISOCodeResponseBody(string CountryISOCodeResult)
    {
        this.CountryISOCodeResult = CountryISOCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CapitalCityRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CapitalCity", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CapitalCityRequestBody Body;
    
    public CapitalCityRequest()
    {
    }
    
    public CapitalCityRequest(CapitalCityRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CapitalCityRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public CapitalCityRequestBody()
    {
    }
    
    public CapitalCityRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CapitalCityResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CapitalCityResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CapitalCityResponseBody Body;
    
    public CapitalCityResponse()
    {
    }
    
    public CapitalCityResponse(CapitalCityResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CapitalCityResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CapitalCityResult;
    
    public CapitalCityResponseBody()
    {
    }
    
    public CapitalCityResponseBody(string CapitalCityResult)
    {
        this.CapitalCityResult = CapitalCityResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryCurrencyRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryCurrencyRequestBody Body;
    
    public CountryCurrencyRequest()
    {
    }
    
    public CountryCurrencyRequest(CountryCurrencyRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryCurrencyRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public CountryCurrencyRequestBody()
    {
    }
    
    public CountryCurrencyRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryCurrencyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryCurrencyResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryCurrencyResponseBody Body;
    
    public CountryCurrencyResponse()
    {
    }
    
    public CountryCurrencyResponse(CountryCurrencyResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryCurrencyResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCurrency CountryCurrencyResult;
    
    public CountryCurrencyResponseBody()
    {
    }
    
    public CountryCurrencyResponseBody(www.oorsprong.org.websamples.countryinfo.tCurrency CountryCurrencyResult)
    {
        this.CountryCurrencyResult = CountryCurrencyResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryFlagRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryFlag", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryFlagRequestBody Body;
    
    public CountryFlagRequest()
    {
    }
    
    public CountryFlagRequest(CountryFlagRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryFlagRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public CountryFlagRequestBody()
    {
    }
    
    public CountryFlagRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryFlagResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryFlagResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryFlagResponseBody Body;
    
    public CountryFlagResponse()
    {
    }
    
    public CountryFlagResponse(CountryFlagResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryFlagResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryFlagResult;
    
    public CountryFlagResponseBody()
    {
    }
    
    public CountryFlagResponseBody(string CountryFlagResult)
    {
        this.CountryFlagResult = CountryFlagResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryIntPhoneCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryIntPhoneCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryIntPhoneCodeRequestBody Body;
    
    public CountryIntPhoneCodeRequest()
    {
    }
    
    public CountryIntPhoneCodeRequest(CountryIntPhoneCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryIntPhoneCodeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public CountryIntPhoneCodeRequestBody()
    {
    }
    
    public CountryIntPhoneCodeRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountryIntPhoneCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryIntPhoneCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountryIntPhoneCodeResponseBody Body;
    
    public CountryIntPhoneCodeResponse()
    {
    }
    
    public CountryIntPhoneCodeResponse(CountryIntPhoneCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountryIntPhoneCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string CountryIntPhoneCodeResult;
    
    public CountryIntPhoneCodeResponseBody()
    {
    }
    
    public CountryIntPhoneCodeResponseBody(string CountryIntPhoneCodeResult)
    {
        this.CountryIntPhoneCodeResult = CountryIntPhoneCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FullCountryInfoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfo", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public FullCountryInfoRequestBody Body;
    
    public FullCountryInfoRequest()
    {
    }
    
    public FullCountryInfoRequest(FullCountryInfoRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class FullCountryInfoRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sCountryISOCode;
    
    public FullCountryInfoRequestBody()
    {
    }
    
    public FullCountryInfoRequestBody(string sCountryISOCode)
    {
        this.sCountryISOCode = sCountryISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FullCountryInfoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public FullCountryInfoResponseBody Body;
    
    public FullCountryInfoResponse()
    {
    }
    
    public FullCountryInfoResponse(FullCountryInfoResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class FullCountryInfoResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryInfo FullCountryInfoResult;
    
    public FullCountryInfoResponseBody()
    {
    }
    
    public FullCountryInfoResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryInfo FullCountryInfoResult)
    {
        this.FullCountryInfoResult = FullCountryInfoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FullCountryInfoAllCountriesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoAllCountries", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public FullCountryInfoAllCountriesRequestBody Body;
    
    public FullCountryInfoAllCountriesRequest()
    {
    }
    
    public FullCountryInfoAllCountriesRequest(FullCountryInfoAllCountriesRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class FullCountryInfoAllCountriesRequestBody
{
    
    public FullCountryInfoAllCountriesRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class FullCountryInfoAllCountriesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoAllCountriesResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public FullCountryInfoAllCountriesResponseBody Body;
    
    public FullCountryInfoAllCountriesResponse()
    {
    }
    
    public FullCountryInfoAllCountriesResponse(FullCountryInfoAllCountriesResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class FullCountryInfoAllCountriesResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryInfo[] FullCountryInfoAllCountriesResult;
    
    public FullCountryInfoAllCountriesResponseBody()
    {
    }
    
    public FullCountryInfoAllCountriesResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryInfo[] FullCountryInfoAllCountriesResult)
    {
        this.FullCountryInfoAllCountriesResult = FullCountryInfoAllCountriesResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountriesUsingCurrencyRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountriesUsingCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountriesUsingCurrencyRequestBody Body;
    
    public CountriesUsingCurrencyRequest()
    {
    }
    
    public CountriesUsingCurrencyRequest(CountriesUsingCurrencyRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountriesUsingCurrencyRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sISOCurrencyCode;
    
    public CountriesUsingCurrencyRequestBody()
    {
    }
    
    public CountriesUsingCurrencyRequestBody(string sISOCurrencyCode)
    {
        this.sISOCurrencyCode = sISOCurrencyCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CountriesUsingCurrencyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CountriesUsingCurrencyResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public CountriesUsingCurrencyResponseBody Body;
    
    public CountriesUsingCurrencyResponse()
    {
    }
    
    public CountriesUsingCurrencyResponse(CountriesUsingCurrencyResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class CountriesUsingCurrencyResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] CountriesUsingCurrencyResult;
    
    public CountriesUsingCurrencyResponseBody()
    {
    }
    
    public CountriesUsingCurrencyResponseBody(www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] CountriesUsingCurrencyResult)
    {
        this.CountriesUsingCurrencyResult = CountriesUsingCurrencyResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfLanguagesByNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfLanguagesByNameRequestBody Body;
    
    public ListOfLanguagesByNameRequest()
    {
    }
    
    public ListOfLanguagesByNameRequest(ListOfLanguagesByNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfLanguagesByNameRequestBody
{
    
    public ListOfLanguagesByNameRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfLanguagesByNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfLanguagesByNameResponseBody Body;
    
    public ListOfLanguagesByNameResponse()
    {
    }
    
    public ListOfLanguagesByNameResponse(ListOfLanguagesByNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfLanguagesByNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tLanguage[] ListOfLanguagesByNameResult;
    
    public ListOfLanguagesByNameResponseBody()
    {
    }
    
    public ListOfLanguagesByNameResponseBody(www.oorsprong.org.websamples.countryinfo.tLanguage[] ListOfLanguagesByNameResult)
    {
        this.ListOfLanguagesByNameResult = ListOfLanguagesByNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfLanguagesByCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfLanguagesByCodeRequestBody Body;
    
    public ListOfLanguagesByCodeRequest()
    {
    }
    
    public ListOfLanguagesByCodeRequest(ListOfLanguagesByCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ListOfLanguagesByCodeRequestBody
{
    
    public ListOfLanguagesByCodeRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ListOfLanguagesByCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public ListOfLanguagesByCodeResponseBody Body;
    
    public ListOfLanguagesByCodeResponse()
    {
    }
    
    public ListOfLanguagesByCodeResponse(ListOfLanguagesByCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class ListOfLanguagesByCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public www.oorsprong.org.websamples.countryinfo.tLanguage[] ListOfLanguagesByCodeResult;
    
    public ListOfLanguagesByCodeResponseBody()
    {
    }
    
    public ListOfLanguagesByCodeResponseBody(www.oorsprong.org.websamples.countryinfo.tLanguage[] ListOfLanguagesByCodeResult)
    {
        this.ListOfLanguagesByCodeResult = ListOfLanguagesByCodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LanguageNameRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public LanguageNameRequestBody Body;
    
    public LanguageNameRequest()
    {
    }
    
    public LanguageNameRequest(LanguageNameRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class LanguageNameRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sISOCode;
    
    public LanguageNameRequestBody()
    {
    }
    
    public LanguageNameRequestBody(string sISOCode)
    {
        this.sISOCode = sISOCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LanguageNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public LanguageNameResponseBody Body;
    
    public LanguageNameResponse()
    {
    }
    
    public LanguageNameResponse(LanguageNameResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class LanguageNameResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string LanguageNameResult;
    
    public LanguageNameResponseBody()
    {
    }
    
    public LanguageNameResponseBody(string LanguageNameResult)
    {
        this.LanguageNameResult = LanguageNameResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LanguageISOCodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageISOCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public LanguageISOCodeRequestBody Body;
    
    public LanguageISOCodeRequest()
    {
    }
    
    public LanguageISOCodeRequest(LanguageISOCodeRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class LanguageISOCodeRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string sLanguageName;
    
    public LanguageISOCodeRequestBody()
    {
    }
    
    public LanguageISOCodeRequestBody(string sLanguageName)
    {
        this.sLanguageName = sLanguageName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class LanguageISOCodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageISOCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
    public LanguageISOCodeResponseBody Body;
    
    public LanguageISOCodeResponse()
    {
    }
    
    public LanguageISOCodeResponse(LanguageISOCodeResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
public partial class LanguageISOCodeResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string LanguageISOCodeResult;
    
    public LanguageISOCodeResponseBody()
    {
    }
    
    public LanguageISOCodeResponseBody(string LanguageISOCodeResult)
    {
        this.LanguageISOCodeResult = LanguageISOCodeResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface CountryInfoServiceSoapTypeChannel : CountryInfoServiceSoapType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CountryInfoServiceSoapTypeClient : System.ServiceModel.ClientBase<CountryInfoServiceSoapType>, CountryInfoServiceSoapType
{
    
    public CountryInfoServiceSoapTypeClient()
    {
    }
    
    public CountryInfoServiceSoapTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CountryInfoServiceSoapTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CountryInfoServiceSoapTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CountryInfoServiceSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ListOfContinentsByNameResponse CountryInfoServiceSoapType.ListOfContinentsByName(ListOfContinentsByNameRequest request)
    {
        return base.Channel.ListOfContinentsByName(request);
    }
    
    public www.oorsprong.org.websamples.countryinfo.tContinent[] ListOfContinentsByName()
    {
        ListOfContinentsByNameRequest inValue = new ListOfContinentsByNameRequest();
        inValue.Body = new ListOfContinentsByNameRequestBody();
        ListOfContinentsByNameResponse retVal = ((CountryInfoServiceSoapType)(this)).ListOfContinentsByName(inValue);
        return retVal.Body.ListOfContinentsByNameResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ListOfContinentsByCodeResponse CountryInfoServiceSoapType.ListOfContinentsByCode(ListOfContinentsByCodeRequest request)
    {
        return base.Channel.ListOfContinentsByCode(request);
    }
    
    public www.oorsprong.org.websamples.countryinfo.tContinent[] ListOfContinentsByCode()
    {
        ListOfContinentsByCodeRequest inValue = new ListOfContinentsByCodeRequest();
        inValue.Body = new ListOfContinentsByCodeRequestBody();
        ListOfContinentsByCodeResponse retVal = ((CountryInfoServiceSoapType)(this)).ListOfContinentsByCode(inValue);
        return retVal.Body.ListOfContinentsByCodeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ListOfCurrenciesByNameResponse CountryInfoServiceSoapType.ListOfCurrenciesByName(ListOfCurrenciesByNameRequest request)
    {
        return base.Channel.ListOfCurrenciesByName(request);
    }
    
    public www.oorsprong.org.websamples.countryinfo.tCurrency[] ListOfCurrenciesByName()
    {
        ListOfCurrenciesByNameRequest inValue = new ListOfCurrenciesByNameRequest();
        inValue.Body = new ListOfCurrenciesByNameRequestBody();
        ListOfCurrenciesByNameResponse retVal = ((CountryInfoServiceSoapType)(this)).ListOfCurrenciesByName(inValue);
        return retVal.Body.ListOfCurrenciesByNameResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ListOfCurrenciesByCodeResponse CountryInfoServiceSoapType.ListOfCurrenciesByCode(ListOfCurrenciesByCodeRequest request)
    {
        return base.Channel.ListOfCurrenciesByCode(request);
    }
    
    public www.oorsprong.org.websamples.countryinfo.tCurrency[] ListOfCurrenciesByCode()
    {
        ListOfCurrenciesByCodeRequest inValue = new ListOfCurrenciesByCodeRequest();
        inValue.Body = new ListOfCurrenciesByCodeRequestBody();
        ListOfCurrenciesByCodeResponse retVal = ((CountryInfoServiceSoapType)(this)).ListOfCurrenciesByCode(inValue);
        return retVal.Body.ListOfCurrenciesByCodeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CurrencyNameResponse CountryInfoServiceSoapType.CurrencyName(CurrencyNameRequest request)
    {
        return base.Channel.CurrencyName(request);
    }
    
    public string CurrencyName(string sCurrencyISOCode)
    {
        CurrencyNameRequest inValue = new CurrencyNameRequest();
        inValue.Body = new CurrencyNameRequestBody();
        inValue.Body.sCurrencyISOCode = sCurrencyISOCode;
        CurrencyNameResponse retVal = ((CountryInfoServiceSoapType)(this)).CurrencyName(inValue);
        return retVal.Body.CurrencyNameResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ListOfCountryNamesByCodeResponse CountryInfoServiceSoapType.ListOfCountryNamesByCode(ListOfCountryNamesByCodeRequest request)
    {
        return base.Channel.ListOfCountryNamesByCode(request);
    }
    
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] ListOfCountryNamesByCode()
    {
        ListOfCountryNamesByCodeRequest inValue = new ListOfCountryNamesByCodeRequest();
        inValue.Body = new ListOfCountryNamesByCodeRequestBody();
        ListOfCountryNamesByCodeResponse retVal = ((CountryInfoServiceSoapType)(this)).ListOfCountryNamesByCode(inValue);
        return retVal.Body.ListOfCountryNamesByCodeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ListOfCountryNamesByNameResponse CountryInfoServiceSoapType.ListOfCountryNamesByName(ListOfCountryNamesByNameRequest request)
    {
        return base.Channel.ListOfCountryNamesByName(request);
    }
    
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] ListOfCountryNamesByName()
    {
        ListOfCountryNamesByNameRequest inValue = new ListOfCountryNamesByNameRequest();
        inValue.Body = new ListOfCountryNamesByNameRequestBody();
        ListOfCountryNamesByNameResponse retVal = ((CountryInfoServiceSoapType)(this)).ListOfCountryNamesByName(inValue);
        return retVal.Body.ListOfCountryNamesByNameResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ListOfCountryNamesGroupedByContinentResponse CountryInfoServiceSoapType.ListOfCountryNamesGroupedByContinent(ListOfCountryNamesGroupedByContinentRequest request)
    {
        return base.Channel.ListOfCountryNamesGroupedByContinent(request);
    }
    
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndNameGroupedByContinent[] ListOfCountryNamesGroupedByContinent()
    {
        ListOfCountryNamesGroupedByContinentRequest inValue = new ListOfCountryNamesGroupedByContinentRequest();
        inValue.Body = new ListOfCountryNamesGroupedByContinentRequestBody();
        ListOfCountryNamesGroupedByContinentResponse retVal = ((CountryInfoServiceSoapType)(this)).ListOfCountryNamesGroupedByContinent(inValue);
        return retVal.Body.ListOfCountryNamesGroupedByContinentResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CountryNameResponse CountryInfoServiceSoapType.CountryName(CountryNameRequest request)
    {
        return base.Channel.CountryName(request);
    }
    
    public string CountryName(string sCountryISOCode)
    {
        CountryNameRequest inValue = new CountryNameRequest();
        inValue.Body = new CountryNameRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        CountryNameResponse retVal = ((CountryInfoServiceSoapType)(this)).CountryName(inValue);
        return retVal.Body.CountryNameResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CountryISOCodeResponse CountryInfoServiceSoapType.CountryISOCode(CountryISOCodeRequest request)
    {
        return base.Channel.CountryISOCode(request);
    }
    
    public string CountryISOCode(string sCountryName)
    {
        CountryISOCodeRequest inValue = new CountryISOCodeRequest();
        inValue.Body = new CountryISOCodeRequestBody();
        inValue.Body.sCountryName = sCountryName;
        CountryISOCodeResponse retVal = ((CountryInfoServiceSoapType)(this)).CountryISOCode(inValue);
        return retVal.Body.CountryISOCodeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CapitalCityResponse CountryInfoServiceSoapType.CapitalCity(CapitalCityRequest request)
    {
        return base.Channel.CapitalCity(request);
    }
    
    public string CapitalCity(string sCountryISOCode)
    {
        CapitalCityRequest inValue = new CapitalCityRequest();
        inValue.Body = new CapitalCityRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        CapitalCityResponse retVal = ((CountryInfoServiceSoapType)(this)).CapitalCity(inValue);
        return retVal.Body.CapitalCityResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CountryCurrencyResponse CountryInfoServiceSoapType.CountryCurrency(CountryCurrencyRequest request)
    {
        return base.Channel.CountryCurrency(request);
    }
    
    public www.oorsprong.org.websamples.countryinfo.tCurrency CountryCurrency(string sCountryISOCode)
    {
        CountryCurrencyRequest inValue = new CountryCurrencyRequest();
        inValue.Body = new CountryCurrencyRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        CountryCurrencyResponse retVal = ((CountryInfoServiceSoapType)(this)).CountryCurrency(inValue);
        return retVal.Body.CountryCurrencyResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CountryFlagResponse CountryInfoServiceSoapType.CountryFlag(CountryFlagRequest request)
    {
        return base.Channel.CountryFlag(request);
    }
    
    public string CountryFlag(string sCountryISOCode)
    {
        CountryFlagRequest inValue = new CountryFlagRequest();
        inValue.Body = new CountryFlagRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        CountryFlagResponse retVal = ((CountryInfoServiceSoapType)(this)).CountryFlag(inValue);
        return retVal.Body.CountryFlagResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CountryIntPhoneCodeResponse CountryInfoServiceSoapType.CountryIntPhoneCode(CountryIntPhoneCodeRequest request)
    {
        return base.Channel.CountryIntPhoneCode(request);
    }
    
    public string CountryIntPhoneCode(string sCountryISOCode)
    {
        CountryIntPhoneCodeRequest inValue = new CountryIntPhoneCodeRequest();
        inValue.Body = new CountryIntPhoneCodeRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        CountryIntPhoneCodeResponse retVal = ((CountryInfoServiceSoapType)(this)).CountryIntPhoneCode(inValue);
        return retVal.Body.CountryIntPhoneCodeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FullCountryInfoResponse CountryInfoServiceSoapType.FullCountryInfo(FullCountryInfoRequest request)
    {
        return base.Channel.FullCountryInfo(request);
    }
    
    public virtual www.oorsprong.org.websamples.countryinfo.tCountryInfo FullCountryInfo(string sCountryISOCode)
    {
        FullCountryInfoRequest inValue = new FullCountryInfoRequest();
        inValue.Body = new FullCountryInfoRequestBody();
        inValue.Body.sCountryISOCode = sCountryISOCode;
        FullCountryInfoResponse retVal = ((CountryInfoServiceSoapType)(this)).FullCountryInfo(inValue);
        return retVal.Body.FullCountryInfoResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    FullCountryInfoAllCountriesResponse CountryInfoServiceSoapType.FullCountryInfoAllCountries(FullCountryInfoAllCountriesRequest request)
    {
        return base.Channel.FullCountryInfoAllCountries(request);
    }
    
    public virtual www.oorsprong.org.websamples.countryinfo.tCountryInfo[] FullCountryInfoAllCountries()
    {
        FullCountryInfoAllCountriesRequest inValue = new FullCountryInfoAllCountriesRequest();
        inValue.Body = new FullCountryInfoAllCountriesRequestBody();
        FullCountryInfoAllCountriesResponse retVal = ((CountryInfoServiceSoapType)(this)).FullCountryInfoAllCountries(inValue);
        return retVal.Body.FullCountryInfoAllCountriesResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CountriesUsingCurrencyResponse CountryInfoServiceSoapType.CountriesUsingCurrency(CountriesUsingCurrencyRequest request)
    {
        return base.Channel.CountriesUsingCurrency(request);
    }
    
    public www.oorsprong.org.websamples.countryinfo.tCountryCodeAndName[] CountriesUsingCurrency(string sISOCurrencyCode)
    {
        CountriesUsingCurrencyRequest inValue = new CountriesUsingCurrencyRequest();
        inValue.Body = new CountriesUsingCurrencyRequestBody();
        inValue.Body.sISOCurrencyCode = sISOCurrencyCode;
        CountriesUsingCurrencyResponse retVal = ((CountryInfoServiceSoapType)(this)).CountriesUsingCurrency(inValue);
        return retVal.Body.CountriesUsingCurrencyResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ListOfLanguagesByNameResponse CountryInfoServiceSoapType.ListOfLanguagesByName(ListOfLanguagesByNameRequest request)
    {
        return base.Channel.ListOfLanguagesByName(request);
    }
    
    public www.oorsprong.org.websamples.countryinfo.tLanguage[] ListOfLanguagesByName()
    {
        ListOfLanguagesByNameRequest inValue = new ListOfLanguagesByNameRequest();
        inValue.Body = new ListOfLanguagesByNameRequestBody();
        ListOfLanguagesByNameResponse retVal = ((CountryInfoServiceSoapType)(this)).ListOfLanguagesByName(inValue);
        return retVal.Body.ListOfLanguagesByNameResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ListOfLanguagesByCodeResponse CountryInfoServiceSoapType.ListOfLanguagesByCode(ListOfLanguagesByCodeRequest request)
    {
        return base.Channel.ListOfLanguagesByCode(request);
    }
    
    public www.oorsprong.org.websamples.countryinfo.tLanguage[] ListOfLanguagesByCode()
    {
        ListOfLanguagesByCodeRequest inValue = new ListOfLanguagesByCodeRequest();
        inValue.Body = new ListOfLanguagesByCodeRequestBody();
        ListOfLanguagesByCodeResponse retVal = ((CountryInfoServiceSoapType)(this)).ListOfLanguagesByCode(inValue);
        return retVal.Body.ListOfLanguagesByCodeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    LanguageNameResponse CountryInfoServiceSoapType.LanguageName(LanguageNameRequest request)
    {
        return base.Channel.LanguageName(request);
    }
    
    public string LanguageName(string sISOCode)
    {
        LanguageNameRequest inValue = new LanguageNameRequest();
        inValue.Body = new LanguageNameRequestBody();
        inValue.Body.sISOCode = sISOCode;
        LanguageNameResponse retVal = ((CountryInfoServiceSoapType)(this)).LanguageName(inValue);
        return retVal.Body.LanguageNameResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    LanguageISOCodeResponse CountryInfoServiceSoapType.LanguageISOCode(LanguageISOCodeRequest request)
    {
        return base.Channel.LanguageISOCode(request);
    }
    
    public string LanguageISOCode(string sLanguageName)
    {
        LanguageISOCodeRequest inValue = new LanguageISOCodeRequest();
        inValue.Body = new LanguageISOCodeRequestBody();
        inValue.Body.sLanguageName = sLanguageName;
        LanguageISOCodeResponse retVal = ((CountryInfoServiceSoapType)(this)).LanguageISOCode(inValue);
        return retVal.Body.LanguageISOCodeResult;
    }
}
